databases:
  - name: thewardrobeapp
    plan: free
    databaseName: thewardrobeapp
    user: thewardrobeapp

services:
  - type: web
    name: thewardrobeapp
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thewardrobeapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
